Creación de filtro para bajas unidades de productos
anything-devs/bike-soft-rest-api pull request #6
Opened 2023-04-10 14:39 UTC by Manuela-Rendon

#4  Se realiza la creación del filtro para obtener la lista de los productos con bajas unidades, la cantidad de bajas unidades se puede cambiar manualmente desde la URL

2023-04-10 16:31 UTC, cristian409 requested changes

2023-04-10 16:31 UTC, cristian409 commented on controllers/Productos.controller.go
> + */
Cambiar el código para que no reciba la cantidad de bajas unidades por parámetro de URL, dado que por requerimientos del Cliente la cantidad es estática, < 5 unidades.
"El filtro de Bajas unidades debe mostrar los productos con cantidad menor a 5 unidades."

2023-04-10 16:31 UTC, cristian409 commented on routes/index.routes.go
> +	router.GET("/productos/filtrados", controllers.FiltroBajasUnidades)
Cambiar el nombre /filtrados, ya que es muy global como información, colocar un nombre más específico.

2023-04-10 20:05 UTC, Manuela-Rendon commented on routes/index.routes.go
> +	router.GET("/productos/filtrados", controllers.FiltroBajasUnidades)
Se cambia el nombre a /filtradosBajasUnidades/:cantidad, así mismo arreglando la ruta y el método para que solo al cambiar el número final de la ruta, este sea el valor mínimo a filtrar

2023-04-11 01:48 UTC, cristian409 approved these changes

2023-04-11 01:49 UTC, merged